scrape_configs:

- job_name: json_exporter
  static_configs:
    - targets:
      - je:7979

- job_name: rates
  metrics_path: /probe
  params:
    module: [rates]
  static_configs:
    - targets:
      - 'https://cash.rbc.ru/cash/json/cash_rates_with_volumes/?city=1&currency=3'
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: je:7979